gatsby-source-filesystem-programmatic-import translate
gatsbyjs/gatsby-pt-BR pull request #188
Opened 2020-01-30 17:17 UTC by thiagorowof

#### Qual o objetivo dessa pull request?

* [x] Adição de uma nova tradução
* [ ] Correção em uma tradução existente

#### Qual arquivo foi traduzido/corrigido?
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/gatsby-source-filesystem-programmatic-importmd
>
https://github.com/thiagorowof/gatsby-pt-BR/blob/gatsby-source-filesystem-programmatic-import/docs/docs/gatsby-source-filesystem-programmatic-import.md

#### Algum comentário em relação a tradução?

2020-05-02 20:28 UTC, henriquepw requested changes
@thiagorowof, esse arquivo tem conflito, poderia resolvê-lo por favor?

2020-05-10 21:35 UTC, thiagorowof commented
> @thiagorowof, esse arquivo tem conflito, poderia resolvê-lo por favor?

Irei ajustar o mais rápido possivel

2020-07-24 23:22 UTC, felipefbs approved these changes

2020-07-29 14:19 UTC, iaurg approved these changes

2020-08-15 23:31 UTC, thayannevls commented
@thiagorowof Se estiver com qualquer dificuldade, só avisar que estamos aqui para ajudar!

2020-11-17 12:04 UTC, henry-ns approved these changes

2025-01-20 16:37 UTC, closed without merging