tradução do customizing-components.md
gatsbyjs/gatsby-pt-BR pull request #197
Opened 2020-02-08 16:01 UTC by AntonioHamilton

#### Qual o objetivo dessa pull request?

* [x] Adição de uma nova tradução
* [ ] Correção em uma tradução existente

#### Qual arquivo foi traduzido/corrigido?
customizing-components.md
***local:*** docs/contributing/customizing-components.md

#### Algum comentário em relação a tradução?
- Acredito que esse arquivo não possa ficar em markdown por causa da tabela, os elementos dela explicitam o markdown e isso pode ser problemático na hora de colocar no site

2020-03-05 23:35 UTC, jessescn submitted a review, later dismissed
Não precisa se preocupar com a tabela

2020-04-14 14:13 UTC, iaurg commented
E ai @AntonioHamilton tudo certo? Pode linkar para mim o documento original? Não encontrei ele no [caminho](https://github.com/gatsbyjs/gatsby-pt-BR/tree/master/docs/contributing) informado.

2020-04-14 14:19 UTC, iaurg requested changes
Olá @AntonioHamilton, obrigado por contribuir. Marquei alguns detalhes, veja o que acha.

2020-04-14 14:19 UTC, iaurg commented on docs/contributing/customizing-components.md
> +# Customizando Componentes
```suggestion
# Customizando Componentes Markdown
```

2020-04-14 14:19 UTC, iaurg commented on docs/contributing/customizing-components.md
> +
```suggestion
**Note**: you can also provide your own custom components to the `MDXProvider` that make them globally available while writing MDX. You can find more details about this pattern in the [Importing and Using Components in MDX guide](/docs/mdx/importing-and-using-components/#make-components-available-globally-as-shortcodes).
```

2020-04-14 14:19 UTC, iaurg commented on docs/contributing/customizing-components.md
> +
Verifiquei no [documento original](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/mdx/customizing-components.md) e faltou esse bloco aqui.

2020-04-14 14:19 UTC, iaurg commented on docs/contributing/customizing-components.md
> +### Como isso funciona?
```suggestion
## Como isso funciona?
```

2020-04-14 14:19 UTC, iaurg commented on docs/contributing/customizing-components.md
> +### Relacionado
```suggestion
## Relacionado
```

2020-04-14 14:19 UTC, iaurg commented on docs/contributing/customizing-components.md
> +Componentes passados para o MDXProvider são usados para renderizar o elemento HTML que o Markdown cria. Isso usa [React's Context API](https://reactjs.org/docs/context.html)
```suggestion
Componentes passados para o MDXProvider são usados para renderizar o elemento HTML que o Markdown cria. Isso usa [React's Context API](https://pt-br.reactjs.org/docs/context.html)
```

2020-06-29 14:09 UTC, henry-ns commented
Como ta indo @AntonioHamilton a tradução?

2020-11-10 16:49 UTC, henry-ns approved these changes

2022-10-11 13:29 UTC, closed without merging