Add component-libraries.md translation
gatsbyjs/gatsby-pt-BR pull request #198
Opened 2020-02-10 18:08 UTC by furlanf

#### Qual o objetivo dessa pull request?

* [x] Adição de uma nova tradução
* [ ] Correção em uma tradução existente

#### Qual arquivo foi traduzido/corrigido?

[component-libraries](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/component-libraries.md)

2020-03-05 23:33 UTC, jessescn requested changes
Muito boa mesmo, apenas vi três coisinhas pra melhorar

2020-03-05 23:33 UTC, jessescn commented on docs/docs/component-libraries.md
> +Bibliotecas de componentes são geralmente armazenadas em um repositório separado. Aplicativos individuais ou websites estão especificados em suas dependências (dentro do `package.json`) qual versão d
```suggestion
Bibliotecas de componentes são geralmente armazenadas em um repositório separado. Aplicativos individuais ou websites especificam em suas dependências (dentro do `package.json`) qual versão de cada componente eles estão usando.
```

2020-03-05 23:33 UTC, jessescn commented on docs/docs/component-libraries.md
> +A segunda abordagem é para a versão de cada componente na biblioteca de componentes. Isto era usado, por exemplo, [por Walmart.com](https://medium.com/walmartlabs/how-to-achieve-reusability-with-reac
```suggestion
A segunda abordagem é para a versão de cada componente na biblioteca de componentes. Isto era usado, por exemplo, [pelo Walmart.com](https://medium.com/walmartlabs/how-to-achieve-reusability-with-react-components-81edeb7fb0e0) -- eles construiram sua biblioteca de componentes com React componentes, criando cada componente separado, versionado por pacotes npm.
```

2020-04-14 23:03 UTC, furlanf commented
@jessescn alterações feitas.

2020-04-15 18:15 UTC, iaurg requested changes
Ótima tradução @furlanf, marquei alguns pontos.

2020-04-15 18:15 UTC, iaurg commented on docs/docs/component-libraries.md
> +Bibliotecas de componentes são frequentementes usadas em sistemas de interface baseados em componentes como React e Vue. Eles são normalmente versionados em repositórios de componentes.
```suggestion
Bibliotecas de componentes são frequentemente utilizadas em sistemas de interface baseados em componentes como React e Vue. Elas são normalmente versionadas em repositórios de componentes.
```

2020-04-15 18:15 UTC, iaurg commented on docs/docs/component-libraries.md
> +- **Criando um design unificado**. Em grandes propriedades da web e aplicativos web, a aparência e sentimento podem divergir através de diferentes seções mantidas por diferentes times. Bibliotecas de
```suggestion
- **Criando um design unificado**. Em grandes propriedades da web e aplicativos web, a aparência e sentimento podem divergir através de diferentes seções mantidas por diferentes times. Bibliotecas de componentes são frequentemente usadas para implementar um [sistema de design](https://www.designsystems.com/).
```

2020-04-15 18:15 UTC, iaurg commented on docs/docs/component-libraries.md
> +A primeira é para a versão global na biblioteca de componentes. Para cada commit dado, a biblioteca tem um número de versão (e.g. `30.3.1`). Qualquer commit atualizando o componente irá então adicion
```suggestion
A primeira é para a versão global na biblioteca de componentes. Para cada commit dado, a biblioteca tem um número de versão (e.g. `30.3.1`). Qualquer commit atualizando o componente irá então adicionar o número de versão de acordo. Ambos, Carbon Design System e Blueprint adotam essa abordagem.
```

2020-04-16 01:54 UTC, furlanf commented
@iaurg, alterações feitas. Obrigado.

2020-04-16 13:32 UTC, henriquepw requested changes
Olá @furlanf, só mais um detalhezinho pra corrigir.

2020-04-16 13:32 UTC, henry-ns commented on docs/docs/component-libraries.md
> +IBM's [Carbon Design System](https://www.carbondesignsystem.com/) e Palantir's [Blueprint](https://blueprintjs.com/) são ambos bons exemplos.
```suggestion
IBM's [Carbon Design System](https://www.carbondesignsystem.com/) e [Blueprint](https://blueprintjs.com/) da Palantir são ambos bons exemplos.
```

2020-04-16 13:37 UTC, furlanf commented
@henry-ns Boa, corrigido. :smiley:

2020-04-16 13:38 UTC, henriquepw approved these changes
:tada:
Agora só aguardar a aprovação de outro reviewer :)

@jessescn, @iaurg , @thayannevls

2020-06-29 14:53 UTC, iaurg requested changes
Ótima tradução @furlanf , marquei apenas um detalhe de escrita.

2020-06-29 14:53 UTC, iaurg commented on docs/docs/component-libraries.md
> +Por exemplo, se um desenvolvedor de recursos precisar alterar uma biblioteca de componentes, o fluxo de trabalho do desenvolvedor normalmente envolve dois pull requests; um para o repositório do comp
```suggestion
Por exemplo, se um desenvolvedor de recursos precisar alterar uma biblioteca de componentes, o fluxo de trabalho do desenvolvedor normalmente envolve dois pull requests; um para o repositório do componente que foi feito alterações, e um para o repositório do site para aumentar a versão do componente.
```

2020-07-11 08:08 UTC, thayannevls requested changes
Muito obrigada pela contribuição! Fiz algumas sugestões, sinta-se livre para adicioná-las ou discuti-las aqui :smile:

2020-07-11 08:08 UTC, thayannevls commented on docs/docs/component-libraries.md
> +- **Evite reinventar a roda**. Bibliotecas de componentes incluem elementos comuns, como carousels ou dropdowns, para evitar a necessidade de equipes individuais reimplementarem estes componentes.
```suggestion
- **Criar um design unificado**. Em grandes propriedades da web e aplicativos web, a aparência e sentimento podem divergir através de diferentes seções mantidas por diferentes times. Bibliotecas de componentes são frequentemente usadas para implementar um [sistema de design](https://www.designsystems.com/).
- **Evitar reinventar a roda**. Bibliotecas de componentes incluem elementos comuns, como carousels ou dropdowns, para evitar a necessidade de equipes individuais reimplementarem estes componentes.
```

2020-07-11 08:08 UTC, thayannevls commented on docs/docs/component-libraries.md
> +A primeira é para a versão global na biblioteca de componentes. Para cada commit dado, a biblioteca tem um número de versão (e.g. `30.3.1`). Qualquer commit atualizando o componente irá então adicion
```suggestion
A primeira é versionar globalmente a biblioteca de componentes. Para cada commit dado, a biblioteca tem um número de versão (e.g. `30.3.1`). Qualquer commit atualizando o componente irá então adicionar o número de versão de acordo. Ambos, Carbon Design System e Blueprint adotam essa abordagem.
```

2020-07-11 08:08 UTC, thayannevls commented on docs/docs/component-libraries.md
> +A segunda abordagem é para a versão de cada componente na biblioteca de componentes. Isto era usado, por exemplo, [pelo Walmart.com](https://medium.com/walmartlabs/how-to-achieve-reusability-with-rea
```suggestion
A segunda abordagem é versionar cada componente separadamente na biblioteca de componentes. Isto era usado, por exemplo, [pelo Walmart.com](https://medium.com/walmartlabs/how-to-achieve-reusability-with-react-components-81edeb7fb0e0) -- eles construíram sua biblioteca de componentes usando React, criando cada componente separadamente, versionado por pacotes npm.
```

2020-07-24 23:39 UTC, felipefbs requested changes

2020-07-24 23:39 UTC, felipefbs commented on docs/docs/component-libraries.md
> +IBM's [Carbon Design System](https://www.carbondesignsystem.com/) e [Blueprint](https://blueprintjs.com/) da Palantir são ambos bons exemplos.
```suggestion
Bons exemplos disso são: O [Carbon Design System](https://www.carbondesignsystem.com/) da IBM e [Blueprint](https://blueprintjs.com/) da Palantir.
```

2020-07-24 23:39 UTC, felipefbs commented on docs/docs/component-libraries.md
> +## Por que bibliotecas de componentes
```suggestion
## Por que usar bibliotecas de componentes
```

2020-07-24 23:39 UTC, felipefbs commented on docs/docs/component-libraries.md
> +- **Criando um design unificado**. Em grandes propriedades da web e aplicativos web, a aparência e sentimento podem divergir através de diferentes seções mantidas por diferentes times. Bibliotecas de
```suggestion
- **Criar um design unificado**. Na internet, aplicações e propriedades de larga escala podem ter diferente aparências e experiencias quando diferentes seções são mantidas por times diferentes. Bibliotecas de componentes são frequentemente usadas para implementar um [sistema de design](https://www.designsystems.com/).
```

2025-01-20 16:37 UTC, closed without merging