Translate using-multiple-gatsby-themes to pt-br
gatsbyjs/gatsby-pt-BR pull request #200
Opened 2020-02-14 02:01 UTC by maykonmenezes

#### Qual o objetivo dessa pull request?

* [X] Adição de uma nova tradução
* [ ] Correção em uma tradução existente

#### Qual arquivo foi traduzido/corrigido?

[using-multiple-gatsby-themes.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/themes/using-multiple-gatsby-themes.md)
#### Algum comentário em relação a tradução?

2020-02-15 18:50 UTC, jessescn requested changes
Obrigado pela tradução, apenas duas besteiras que eu queria q tu desse uma olhada

2020-02-15 18:50 UTC, jessescn commented on docs/docs/themes/using-multiple-gatsby-themes.md
> +Título: Usando Múltiplos Temas Gatsby
```suggestion
title: Usando Múltiplos Temas Gatsby
```

2020-02-15 18:50 UTC, jessescn commented on docs/docs/themes/using-multiple-gatsby-themes.md
> +![A rota de 'notas' criada pelo gatsby-theme-starter](../images/gatsby-theme-starter-notes.png)
```suggestion
![A rota de `notas` criada pelo gatsby-theme-starter](../images/gatsby-theme-starter-notes.png)
```

2020-02-16 12:20 UTC, maykonmenezes commented on docs/docs/themes/using-multiple-gatsby-themes.md
> +Título: Usando Múltiplos Temas Gatsby
vou corrigir ;)

2020-02-20 19:00 UTC, maykonmenezes commented
tudo certo com meu pr?

2020-02-24 17:06 UTC, iaurg submitted a review, later dismissed
Ótimo Maykon, obrigado pela tradução e contribuição.

2020-02-28 13:57 UTC, maykonmenezes commented on docs/docs/themes/using-multiple-gatsby-themes.md
> +![A rota de 'notas' criada pelo gatsby-theme-starter](../images/gatsby-theme-starter-notes.png)
@jessescn tudo certo com o pr agora? ja faz algum tempo que corrigi o que voce pediu

2020-03-02 13:55 UTC, maykonmenezes commented
@iaurg @jessescn  já posso pegar outra tradução? esse PR já tem bastante tempo e ainda não foi mergeado.

2020-03-05 23:21 UTC, jessescn submitted a review, later dismissed

2020-03-05 23:25 UTC, jessescn requested changes

2020-03-05 23:25 UTC, jessescn commented on docs/docs/themes/using-multiple-gatsby-themes.md
> +O tema starter inclui ambos pacotes de temas (`gatsby-theme-blog` e `gatsby-theme-notes`) no arquivo `gatsby-config.js` do tema starter.
```suggestion
```
Apaga essa parte que eu deixei sem querer quando fui corrigir os conflitos

2020-06-29 14:11 UTC, henry-ns commented
Como está indo a a tradução @maykonmenezes?

2025-01-20 16:37 UTC, closed without merging