translation of gatsby-lifecycle-apis.md
gatsbyjs/gatsby-pt-BR pull request #219
Opened 2020-03-02 20:02 UTC by Lucaas-Eduardo

#### Qual o objetivo dessa pull request?

* [x ] Adição de uma nova tradução
* [ ] Correção em uma tradução existente

#### Qual arquivo foi traduzido/corrigido?
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/gatsby-lifecycle-apis.md

#### Algum comentário em relação a tradução?

2020-03-05 23:07 UTC, jessescn requested changes
Obrigado pela contribuição, apontei algumas besteiras mas em geral ta muito bom :)

2020-03-05 23:07 UTC, jessescn commented on docs/docs/gatsby-lifecycle-apis.md
> +- Os plugins são facéis de abrir e reutilizar. Eles são apenas pacotes do NPM.
```suggestion
- Os plugins são facéis de abrir e reutilizar. Eles são apenas pacotes NPM.   
```

2020-03-05 23:07 UTC, jessescn commented on docs/docs/gatsby-lifecycle-apis.md
> +O modelo a seguir fornece uma visão geral conceitual de como os dados são originados e transformados no processo de construção de um site de Gatsby:
```suggestion
O modelo a seguir fornece uma visão geral conceitual de como os dados são originados e transformados no processo de construção de um site Gatsby:
```

2020-03-24 18:27 UTC, jessescn submitted a review, later dismissed
Por mim parece ótimo, obrigado pela contribuição

2020-03-29 15:27 UTC, iaurg requested changes
Obrigado por contribuir, adicionei o comentário de alguns pontos, veja se é do arquivo ou está antigo. Parece que mesclou.

2020-03-29 15:27 UTC, iaurg commented on docs/docs/gatsby-lifecycle-apis.md
> +import LayerModel from "../../www/src/components/layer-model"
```suggestion
```

2020-03-29 15:27 UTC, iaurg commented on docs/docs/gatsby-lifecycle-apis.md
>  Gatsby provides a rich set of lifecycle APIs to hook into its bootstrap,
```suggestion
```

2020-03-29 15:27 UTC, iaurg commented on docs/docs/gatsby-lifecycle-apis.md
>  build, and client runtime operations.
```suggestion
```

2020-03-29 15:27 UTC, iaurg commented on docs/docs/gatsby-lifecycle-apis.md
>  ## High level Overview
```suggestion
```

2020-03-29 15:27 UTC, iaurg commented on docs/docs/gatsby-lifecycle-apis.md
>  During the main bootstrap sequence, Gatsby (in this order):
```suggestion
```

2020-03-29 15:27 UTC, iaurg commented on docs/docs/gatsby-lifecycle-apis.md
>  ## Build sequence
```suggestion
```

2020-03-29 15:27 UTC, iaurg commented on docs/docs/gatsby-lifecycle-apis.md
>  - writes page redirects (if any) to `.cache/redirects.json`
Esse foi adicionado depois?

2020-03-29 15:27 UTC, iaurg commented on docs/docs/gatsby-lifecycle-apis.md
>  - the [onPostBootstrap](/docs/node-apis/#onPostBootstrap) lifecycle is executed
Esse foi adicionado depois também?

2020-04-03 18:07 UTC, Lucaas-Eduardo commented on docs/docs/gatsby-lifecycle-apis.md
>  - the [onPostBootstrap](/docs/node-apis/#onPostBootstrap) lifecycle is executed
Acredito que tenham adicionado depois

2020-04-03 18:08 UTC, Lucaas-Eduardo commented on docs/docs/gatsby-lifecycle-apis.md
>  - the [onPostBootstrap](/docs/node-apis/#onPostBootstrap) lifecycle is executed
faço a traduçao?

2020-04-15 15:04 UTC, henry-ns commented on docs/docs/gatsby-lifecycle-apis.md
>  - the [onPostBootstrap](/docs/node-apis/#onPostBootstrap) lifecycle is executed
sim

2020-04-16 19:43 UTC, Lucaas-Eduardo commented on docs/docs/gatsby-lifecycle-apis.md
>  - the [onPostBootstrap](/docs/node-apis/#onPostBootstrap) lifecycle is executed
pronto

2020-06-09 11:54 UTC, Lucaas-Eduardo commented
está faltando algo?

2020-06-13 15:29 UTC, henry-ns commented
@Lucaas-Eduardo tem partes ainda não traduzidas

2020-07-11 08:21 UTC, thayannevls commented
Como está o processo de tradução nesse arquivo @Lucaas-Eduardo ? Precisa de alguma ajuda?

2025-01-20 16:37 UTC, closed without merging