Translated sourcing-from-sanity.md to pt-br
gatsbyjs/gatsby-pt-BR pull request #264
Opened 2020-06-28 21:49 UTC by zambo

Translated the document to pt-br keeping the code examples as it is and translating a few of the technichal terms to pt-br, keeping the ones that doesn't need translation.

#### Qual o objetivo dessa pull request?

* [x] Adição de uma nova tradução
* [ ] Correção em uma tradução existente

#### Qual arquivo foi traduzido/corrigido?
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/sourcing-from-sanity.md

#### Algum comentário em relação a tradução?
Dificuldade de traduzir alguns termos como query, fetch, dataset (específico do Sanity) e Portable Text.

2020-06-29 13:59 UTC, henriquepw requested changes
Obrigado pela tradução @zambo :tada:

Fiz algumas sugestões, poderia da uma olhada?

2020-06-29 13:59 UTC, henry-ns commented on docs/docs/sourcing-from-sanity.md
> +Você também pode conferir este [exemplo de site institucional](https://github.com/sanity-io/example-company-website-gatsby-sanity-combo) que nós criamos. Ele foi construído com um backend configurado
```suggestion
Você também pode conferir este [exemplo de site institucional](https://github.com/sanity-io/example-company-website-gatsby-sanity-combo) que nós criamos. Ele foi construído com um backend configurado com o Sanity Studio e o frontend com Gatsby, que você pode usar para dar início ao seu projeto em poucos minutos. Esta pode ser uma boa referência de como construir um site usando conteúdo estruturado. Siga as instruções neste README.md para dar início ao seu projeto.
```

2020-06-29 13:59 UTC, henry-ns commented on docs/docs/sourcing-from-sanity.md
> +| overlayDrafts | boolean | `false` | Defina como true para que os rascunhos sejam utilizados no lugar das suas versões publicadas. Por padrão, os rascunhos serão ignorados.
```suggestion
| overlayDrafts | boolean | `false` | Defina como `true` para que os rascunhos sejam utilizados no lugar das suas versões publicadas. Por padrão, os rascunhos serão ignorados.                                      |
```

2020-06-29 13:59 UTC, henry-ns commented on docs/docs/sourcing-from-sanity.md
> +| watchMode     | boolean | `false` | Defina como true para que os rascunhos sejam utilizados no lugar das suas versões publicadas. Por padrão, os rascunhos serão ignorados.
```suggestion
| watchMode     | boolean | `false` | Defina como `true` para que os rascunhos sejam utilizados no lugar das suas versões publicadas. Por padrão, os rascunhos serão ignorados.                                                          |
```

2020-06-29 13:59 UTC, henry-ns commented on docs/docs/sourcing-from-sanity.md
> +Ao [implantar uma API GraphQL](https://www.sanity.io/help/graphql-beta) no seu projeto, o Sanity pode inspecionar entender quais tipos e campos estão disponíveis no seu esquema de dados e disponibili
```suggestion
Ao [implantar uma API GraphQL](https://www.sanity.io/help/graphql-beta) no seu projeto, o Sanity pode inspecionar e entender quais tipos e campos estão disponíveis no seu esquema de dados e disponibiliza-los para evitar este problema. Uma vez que a sua API está implantada ela será aplicada de forma transparente no seu projeto. Se você já implantou sua API e ainda esta tendo problemas similares, lembre-se que caso o seu esquema de dados tenha mudado, você deve implantar sua API novamente.
```

2020-06-29 13:59 UTC, henry-ns commented on docs/docs/sourcing-from-sanity.md
> +A consulta acima vai buscar por todos os projetos que possuem o campo `slug.current` definido, e gerar as páginas para cada um deles, disponível como `/project/ <slug-do-projeto>` usando o template d
```suggestion
A consulta acima vai buscar por todos os projetos que possuem o campo `slug.current` definido, e gerar as páginas para cada um deles, disponível como `/project/ <slug-do-projeto>` usando o template definido em `src/templates/project.js` como a base para estas páginas.
```

2020-06-29 13:59 UTC, henry-ns commented on docs/docs/sourcing-from-sanity.md
> +Arrays e objetos na raiz do documento receberão um campo "raw JSON" adicional, representado através do `_raw<NomeDoCampo>`. Por exemplo, um campo chamado de `body` será mapeado para `_rawBody`. É imp
```suggestion
Arrays e objetos na raiz do documento receberão um campo "raw JSON" adicional, representado através do `_raw<NomeDoCampo>`. Por exemplo, um campo chamado de `body` será mapeado para `_rawBody`. É importante lembrar que isto só acontece para items no topo da estrutura de dados (documentos).
```

2020-06-29 14:27 UTC, zambo commented
Sugestões aceitas 👍

2020-06-29 15:01 UTC, henriquepw approved these changes
Aprovado! :dancers: 

Agora só aguardar por +1 aprovação :eyes:

2020-08-08 11:56 UTC, iaurg requested changes
Ótima tradução @zambo, marquei apenas uma palavra que ficou faltando.

2020-08-08 11:56 UTC, iaurg commented on docs/docs/sourcing-from-sanity.md
> +Durante o desenvolvimento, pode ser útil receber atualizações de conteúdo sem a necessidade de reiniciar o processo no terminal. Configurando o `watchMode` para `true`, este plugin irá monitorar qual
```suggestion
Durante o desenvolvimento, pode ser útil receber atualizações de conteúdo sem a necessidade de reiniciar o processo no terminal. Configurando o `watchMode` para `true`, este plugin irá monitorar qualquer alteração de conteúdo no CMS. Quando uma alteração é detectada, o documento em questão é atualizado em tempo real e você poderá ver a alteração imediatamente.
```

2024-12-31 19:55 UTC, closed without merging