Tradução asset-prefix.md
gatsbyjs/gatsby-pt-BR pull request #300
Opened 2020-10-09 21:40 UTC by fillipeags

#### Qual o objetivo dessa pull request?

* [x] Adição de uma nova tradução
* [ ] Correção em uma tradução existente

#### Qual arquivo foi traduzido/corrigido?
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/asset-prefix.md

#### Algum comentário em relação a tradução?
Optei por não tentar traduzir o termo asset-prefix visto que faz referencia ao nome da feature

2020-10-13 11:46 UTC, henry-ns requested changes
Obrigado pela tradução, fiz apenas algumas sugestões de correções ortográficas.

2020-10-13 11:46 UTC, henry-ns commented on docs/docs/asset-prefix.md
> +A funcionalidade `assetPrefix` esta disponível a partir do gatsby@2.4.0, para que você possa perfeitamente usar os Gatsby assets hospedados com domínios diferentes. Para usar tal funcionalidade, cert
```suggestion
A funcionalidade `assetPrefix` está disponível a partir do gatsby@2.4.0, para que você possa perfeitamente usar os Gatsby assets hospedados com domínios diferentes. Para usar tal funcionalidade, certifique-se que sua versão do `gatsby` presente no seu arquivo `package.json` esteja ao menos na versão `2.4.0`.
```

2020-10-13 11:46 UTC, henry-ns commented on docs/docs/asset-prefix.md
> +Ao fazer o build com um `assetPrefix`, necessita-se da flag `--prefix-paths`. Caso essa flag não seja específicada, a opção será ignorada durante o build da aplicação e o conteúdo será geradao como s
```suggestion
Ao fazer o build com um `assetPrefix`, necessita-se da flag `--prefix-paths`. Caso essa flag não seja especificada, a opção será ignorada durante o build da aplicação e o conteúdo será gerado como se estivesse hospedado em um mesmo domínio. Para garantir que sua build seja gerada corretamente, use o seguinte comando: 
```

2020-10-13 11:46 UTC, henry-ns commented on docs/docs/asset-prefix.md
> +### Usando o`onPostBuild`
```suggestion
### Usando o `onPostBuild`
```

2020-10-13 11:46 UTC, henry-ns commented on docs/docs/asset-prefix.md
> +É isso! Você já possui uma aplicação preparada para deploy com seus assets a partir de um CDN e seus arquivos principais (ex: Arquivos HTML) podem ser hospeados em um diferente domínio.
```suggestion
É isso! Você já possui uma aplicação preparada para deploy com seus assets a partir de um CDN e seus arquivos principais (ex: Arquivos HTML) podem ser hospedados em um diferente domínio.
```

2020-10-13 11:46 UTC, henry-ns commented on docs/docs/asset-prefix.md
> +Utilizando API Hook [`onPostBuild`](/docs/node-apis/#onPostBuild). Isso pode ser usado para fazer o deploy do seu contéudo ao CDN, da seguinte forma:
```suggestion
Utilizando API Hook [`onPostBuild`](/docs/node-apis/#onPostBuild). Isso pode ser usado para fazer o deploy do seu conteúdo ao CDN, da seguinte forma:
```

2020-10-13 11:46 UTC, henry-ns commented on docs/docs/asset-prefix.md
> +A funcionalidade [`pathPrefix`](/docs/path-prefix/) pode ser vista de forma levemente relacionada com a funcionalidade aqui apresentada. Essa funcionalidade permite que _todo_ o conteúdo do seu site
```suggestion
A funcionalidade [`pathPrefix`](/docs/path-prefix/) pode ser vista de forma levemente relacionada com a funcionalidade aqui apresentada. Essa funcionalidade permite que _todo_ o conteúdo do seu site seja prefixado com algumas constantes prefix, por exemplo, você pode querer que seu blog seja hospedado a partir de `/blog` ao invés do diretório raiz do projeto.
```

2020-10-13 11:46 UTC, henry-ns commented on docs/docs/asset-prefix.md
> +   Você pode encontrar a maior parte buscando pela variável `self.__precacheManifest` gerada em `sw.js`. Lembre-se de também incluir o própio `sw.js`, e qualquer ícone referenciado em seu `manifest.w
```suggestion
   Você pode encontrar a maior parte buscando pela variável `self.__precacheManifest` gerada em `sw.js`. Lembre-se de também incluir o próprio `sw.js`, e qualquer ícone referenciado em seu `manifest.webmanifest` caso tenha um. Para verificar se o seu service worker está funcionando como o esperado, verifique em Application → Service Workers na aba dev tools em seus browser, checando qualquer recurso que tenha falhado na sua aba Console/Network.
```

2020-10-13 11:51 UTC, fillipeags commented
Olá, acabei não percebendo os erros, já commitei as sugestões

2020-10-14 22:59 UTC, henry-ns approved these changes
show

2024-02-28 00:09 UTC, closed without merging